[2022-12-13 15:22:28,518] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_tripdata1_dag.download_dataset_task manual__2022-12-12T15:20:27.855458+00:00 [queued]>
[2022-12-13 15:22:28,573] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_tripdata1_dag.download_dataset_task manual__2022-12-12T15:20:27.855458+00:00 [queued]>
[2022-12-13 15:22:28,574] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-13 15:22:28,574] {taskinstance.py:1239} INFO - Starting attempt 4 of 5
[2022-12-13 15:22:28,574] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-13 15:22:28,614] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-12-12 15:20:27.855458+00:00
[2022-12-13 15:22:28,631] {standard_task_runner.py:52} INFO - Started process 20257 to run task
[2022-12-13 15:22:28,650] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_tripdata1_dag', 'download_dataset_task', 'manual__2022-12-12T15:20:27.855458+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_tripdata1_dag.py', '--cfg-path', '/tmp/tmpp7fa9l8z', '--error-file', '/tmp/tmpcfvilnkh']
[2022-12-13 15:22:28,663] {standard_task_runner.py:77} INFO - Job 196: Subtask download_dataset_task
[2022-12-13 15:22:28,873] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_tripdata1_dag.download_dataset_task manual__2022-12-12T15:20:27.855458+00:00 [running]> on host c90fde5b5e35
[2022-12-13 15:22:29,072] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_tripdata1_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T15:20:27.855458+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T15:20:27.855458+00:00
[2022-12-13 15:22:29,074] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-13 15:22:29,075] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://storage.cloud.google.com/data-fellowship08-nyoba/data-fellowship08-nyoba/part-00000-64ea0de6-d39a-42f0-9ba5-2200d99d66d6-c000.snappy.parquet > /opt/***/data-fellowship08-nyoba/part-00000-64ea0de6-d39a-42f0-9ba5-2200d99d66d6-c000.snappy.parquet']
[2022-12-13 15:22:29,130] {subprocess.py:85} INFO - Output:
[2022-12-13 15:22:29,161] {subprocess.py:89} INFO - bash: /opt/***/data-fellowship08-nyoba/part-00000-64ea0de6-d39a-42f0-9ba5-2200d99d66d6-c000.snappy.parquet: No such file or directory
[2022-12-13 15:22:29,162] {subprocess.py:93} INFO - Command exited with return code 1
[2022-12-13 15:22:29,196] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-13 15:22:29,216] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_tripdata1_dag, task_id=download_dataset_task, execution_date=20221212T152027, start_date=20221213T152228, end_date=20221213T152229
[2022-12-13 15:22:29,263] {standard_task_runner.py:92} ERROR - Failed to execute job 196 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-13 15:22:29,301] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-12-13 15:22:29,403] {dagrun.py:628} WARNING - Failed to get task '<TaskInstance: data_ingestion_tripdata1_dag.format_to_parquet_task manual__2022-12-12T15:20:27.855458+00:00 [removed]>' for dag 'data_ingestion_tripdata1_dag'. Marking it as removed.
[2022-12-13 15:22:29,429] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
