[2022-12-13 14:43:44,000] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_tripdata1_dag.format_to_parquet_task manual__2022-12-12T15:20:27.855458+00:00 [queued]>
[2022-12-13 14:43:44,029] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_tripdata1_dag.format_to_parquet_task manual__2022-12-12T15:20:27.855458+00:00 [queued]>
[2022-12-13 14:43:44,029] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-13 14:43:44,029] {taskinstance.py:1239} INFO - Starting attempt 8 of 9
[2022-12-13 14:43:44,029] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-13 14:43:44,052] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2022-12-12 15:20:27.855458+00:00
[2022-12-13 14:43:44,068] {standard_task_runner.py:52} INFO - Started process 18741 to run task
[2022-12-13 14:43:44,085] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_tripdata1_dag', 'format_to_parquet_task', 'manual__2022-12-12T15:20:27.855458+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_tripdata1_dag.py', '--cfg-path', '/tmp/tmpj1fr24iw', '--error-file', '/tmp/tmp261u61pm']
[2022-12-13 14:43:44,089] {standard_task_runner.py:77} INFO - Job 178: Subtask format_to_parquet_task
[2022-12-13 14:43:44,224] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_tripdata1_dag.format_to_parquet_task manual__2022-12-12T15:20:27.855458+00:00 [running]> on host c90fde5b5e35
[2022-12-13 14:43:44,346] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_tripdata1_dag
AIRFLOW_CTX_TASK_ID=format_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T15:20:27.855458+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T15:20:27.855458+00:00
[2022-12-13 14:43:44,665] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_tripdata1_dag.py", line 37, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 867, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 876, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: CSV parse error: Expected 96 columns, got 5: /*# sourceURL=/_/mss/boq-identity/_/ss/k=boq-identity.AccountsSignInUi.RYsx4bNSLR8.L.W.O/am=jhEA ...
[2022-12-13 14:43:44,729] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_tripdata1_dag, task_id=format_to_parquet_task, execution_date=20221212T152027, start_date=20221213T144344, end_date=20221213T144344
[2022-12-13 14:43:44,803] {standard_task_runner.py:92} ERROR - Failed to execute job 178 for task format_to_parquet_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_tripdata1_dag.py", line 37, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 867, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 876, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: CSV parse error: Expected 96 columns, got 5: /*# sourceURL=/_/mss/boq-identity/_/ss/k=boq-identity.AccountsSignInUi.RYsx4bNSLR8.L.W.O/am=jhEA ...
[2022-12-13 14:43:44,825] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-12-13 14:43:44,927] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
