[2022-12-12 15:25:45,529] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_tripdata1_dag.local_to_gcs_task scheduled__2022-12-11T00:00:00+00:00 [queued]>
[2022-12-12 15:25:45,549] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_tripdata1_dag.local_to_gcs_task scheduled__2022-12-11T00:00:00+00:00 [queued]>
[2022-12-12 15:25:45,549] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 15:25:45,549] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-12-12 15:25:45,549] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 15:25:45,571] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-12-11 00:00:00+00:00
[2022-12-12 15:25:45,582] {standard_task_runner.py:52} INFO - Started process 1283 to run task
[2022-12-12 15:25:45,591] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_tripdata1_dag', 'local_to_gcs_task', 'scheduled__2022-12-11T00:00:00+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_tripdata1_dag.py', '--cfg-path', '/tmp/tmpzn1zouae', '--error-file', '/tmp/tmpinbcw0jd']
[2022-12-12 15:25:45,593] {standard_task_runner.py:77} INFO - Job 135: Subtask local_to_gcs_task
[2022-12-12 15:25:45,704] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_tripdata1_dag.local_to_gcs_task scheduled__2022-12-11T00:00:00+00:00 [running]> on host bfc90b1132c2
[2022-12-12 15:25:45,830] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_tripdata1_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-11T00:00:00+00:00
[2022-12-12 15:25:45,852] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_tripdata1_dag.py", line 53, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rsa-key-20221208/dags/tripdata1.parquet'
[2022-12-12 15:25:45,874] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=data_ingestion_tripdata1_dag, task_id=local_to_gcs_task, execution_date=20221211T000000, start_date=20221212T152545, end_date=20221212T152545
[2022-12-12 15:25:45,897] {standard_task_runner.py:92} ERROR - Failed to execute job 135 for task local_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_tripdata1_dag.py", line 53, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rsa-key-20221208/dags/tripdata1.parquet'
[2022-12-12 15:25:45,935] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-12-12 15:25:46,003] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
