[2022-12-08 15:12:53,942] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_taxizone_dag.format_to_parquet_task manual__2022-12-08T14:46:24.822841+00:00 [queued]>
[2022-12-08 15:12:53,954] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_taxizone_dag.format_to_parquet_task manual__2022-12-08T14:46:24.822841+00:00 [queued]>
[2022-12-08 15:12:53,955] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-08 15:12:53,955] {taskinstance.py:1239} INFO - Starting attempt 5 of 6
[2022-12-08 15:12:53,955] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-08 15:12:53,969] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2022-12-08 14:46:24.822841+00:00
[2022-12-08 15:12:53,977] {standard_task_runner.py:52} INFO - Started process 239 to run task
[2022-12-08 15:12:53,984] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_taxizone_dag', 'format_to_parquet_task', 'manual__2022-12-08T14:46:24.822841+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_taxizone_dag.py', '--cfg-path', '/tmp/tmpeh_0jtqr', '--error-file', '/tmp/tmpjvn8a3ve']
[2022-12-08 15:12:53,985] {standard_task_runner.py:77} INFO - Job 70: Subtask format_to_parquet_task
[2022-12-08 15:12:54,051] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_taxizone_dag.format_to_parquet_task manual__2022-12-08T14:46:24.822841+00:00 [running]> on host 3fa8598b66ab
[2022-12-08 15:12:54,123] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_taxizone_dag
AIRFLOW_CTX_TASK_ID=format_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-08T14:46:24.822841+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-08T14:46:24.822841+00:00
[2022-12-08 15:12:54,266] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_taxizone_dag.py", line 59, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 867, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 876, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Empty CSV file
[2022-12-08 15:12:54,289] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_taxizone_dag, task_id=format_to_parquet_task, execution_date=20221208T144624, start_date=20221208T151253, end_date=20221208T151254
[2022-12-08 15:12:54,310] {standard_task_runner.py:92} ERROR - Failed to execute job 70 for task format_to_parquet_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_taxizone_dag.py", line 59, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 867, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 876, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Empty CSV file
[2022-12-08 15:12:54,329] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-12-08 15:12:54,383] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
