[2022-12-04 17:38:59,430] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.format_to_csv_task scheduled__2022-12-03T00:00:00+00:00 [queued]>
[2022-12-04 17:38:59,451] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.format_to_csv_task scheduled__2022-12-03T00:00:00+00:00 [queued]>
[2022-12-04 17:38:59,451] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 17:38:59,451] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 17:38:59,451] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 17:38:59,481] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_to_csv_task> on 2022-12-03 00:00:00+00:00
[2022-12-04 17:38:59,492] {standard_task_runner.py:52} INFO - Started process 252 to run task
[2022-12-04 17:38:59,500] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'format_to_csv_task', 'scheduled__2022-12-03T00:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmplz_lea05', '--error-file', '/tmp/tmp4t17nz_v']
[2022-12-04 17:38:59,502] {standard_task_runner.py:77} INFO - Job 63: Subtask format_to_csv_task
[2022-12-04 17:38:59,591] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.format_to_csv_task scheduled__2022-12-03T00:00:00+00:00 [running]> on host ab1ef7cf54a4
[2022-12-04 17:38:59,672] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=format_to_csv_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-03T00:00:00+00:00
[2022-12-04 17:38:59,674] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 33, in format_to_csv
    json_data = src_file.json()
AttributeError: 'str' object has no attribute 'json'
[2022-12-04 17:38:59,694] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=format_to_csv_task, execution_date=20221203T000000, start_date=20221204T173859, end_date=20221204T173859
[2022-12-04 17:38:59,716] {standard_task_runner.py:92} ERROR - Failed to execute job 63 for task format_to_csv_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 33, in format_to_csv
    json_data = src_file.json()
AttributeError: 'str' object has no attribute 'json'
[2022-12-04 17:38:59,757] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-12-04 17:38:59,815] {dagrun.py:628} WARNING - Failed to get task '<TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2022-12-03T00:00:00+00:00 [removed]>' for dag 'data_ingestion_gcs_dag'. Marking it as removed.
[2022-12-04 17:38:59,833] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
